/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:66c6b922-28d1-4a4b-bf39-45df6c3f6766",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_iFdnLwJPx",
    "aws_user_pools_web_client_id": "1jlrlsmrtvq63vpp6vaafrjr46",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://saiuwhxs3vbthirvv7to2unmca.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
